# pre-commit-config.yaml
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-added-large-files
        args: [ '--maxkb=500' ]
      - id: check-json
      - id: check-merge-conflict
      - id: check-toml
      - id: check-yaml
      - id: debug-statements
      #      - id: mixed-line-ending
      #        args: [ --fix=crlf ]
      - id: no-commit-to-branch
        args: [ --branch, master ]
      - id: pretty-format-json
        args: [ --autofix, --no-sort-keys ]
      - id: trailing-whitespace
        args: [ --markdown-linebreak-ext=md ]

  - repo: https://github.com/executablebooks/mdformat
    rev: 0.7.22  # Use the ref you want to point at
    hooks:
      - id: mdformat
        args: [ --end-of-line, crlf, README.md, ReleaseNotes.md ]
        additional_dependencies:
          - mdformat-black
          - mdformat-gfm
          - mdformat_frontmatter

  - repo: https://github.com/rstcheck/rstcheck
    rev: v6.2.4
    hooks:
      - id: rstcheck
        additional_dependencies: [ sphinx ]
        args: [ "--config", ".rstcheck.cfg" ]

  - repo: https://github.com/asottile/pyupgrade
    rev: v3.19.1
    hooks:
      - id: pyupgrade
        args: [ --py312-plus ]

  - repo: https://github.com/pycqa/isort
    rev: 6.0.1
    hooks:
      - id: isort
        args: [ "--profile", "black", "--filter-files", "--force-single-line-imports",
                "--force-alphabetical-sort-within-sections", "--py", "auto" ]

  - repo: https://github.com/codespell-project/codespell
    rev: v2.4.1
    hooks:
      - id: codespell
        args: [ --write, --toml, pyproject.toml ]
        additional_dependencies:
          - tomli

  - repo: https://github.com/psf/black
    rev: 25.1.0
    hooks:
    - id: black
      language_version: python3

  - repo: https://github.com/pycqa/flake8
    rev: 7.2.0
    hooks:
    - id: flake8
      language_version: python3
      exclude: 'templates'
