#docker-compose.yaml

services:
  db:
    container_name: "${PROJECT_NAME}_db"
    image: mysql:8.0.34
    command: mysqld --default-authentication-plugin=mysql_native_password
    environment:
      INSTALLER_USER_ID: "${INSTALLER_USER_ID}"
      INSTALLER_USER_PWD: "${INSTALLER_USER_PWD}"
      MYSQL_DATABASE: "${MYSQL_DATABASE}"
      MYSQL_HOST: "${MYSQL_HOST}"
      MYSQL_USER: "${MYSQL_USER}"
      MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
      PROJECT_NAME: "${PROJECT_NAME}"
    ports:
      - "${MYSQL_TCP_PORT}:3306"
    volumes:
      - ./scripts/setup_db.sql:/docker-entrypoint-initdb.d/setup_db.sql:ro
