[0.0.10]
Title = "Version 0.0.10"
Description = [ 'Minimum value proposition.', 'Implemented commit, push and tag']
GitHubIssues = []

[0.0.9]
Title = "Version 0.0.9"
Description = [ 'Build branchnew.', 'Fixed the pre-commit hooks that did not work.']
GitHubIssues = []

[0.0.8]
Title = "Version 0.0.8"
Description = [ 'Build commitdef, commitcust and commitpre']
GitHubIssues = []

[0.0.7]
Title = "Version 0.0.7"
Description = [ 'Add pydntic to requirements',]
GitHubIssues = []

[0.0.6]
Title = "Version 0.0.6"
Description = [ 'Automate the entry point #2.',]
GitHubIssues = []

[0.0.5]
Title = "Version 0.0.5"
Description = [ 'Automate the entry point #2.',]
GitHubIssues = []

[0.0.4]
Title = "Version 0.0.4"
Description = [ 'Automate the entry point.', '']
GitHubIssues = []

[0.0.3]
Title = "Version 0.0.3"
Description = [ 'Change minimum requirement for Python to 3.10.',]
GitHubIssues = []

[0.0.2]
Title = "Version 0.0.2"
Description = [ 'Fixed "set_env" import module references.',]
GitHubIssues = []

[0.0.2]
Title = "Version 0.0.2"
Description = [ 'Implement "set_env" & "adda"',]
GitHubIssues = []

[0.0.1]
Title = "Version 0.0.1"
Description = [ 'Implement "set_env" & "adda"',]
GitHubIssues = []

[0.0.0]
Title = "Version 0.0.0"
Description = [ "Creation of the project",]
GitHubIssues = [1]
