[0.0.4]
Title = "Version 0.0.4"
Description = [ 'Automate the entry point.', '']
GitHubIssues = []

[0.0.3]
Title = "Version 0.0.3"
Description = [ 'Change minimum requirement for Python to 3.10.',]
GitHubIssues = []

[0.0.2]
Title = "Version 0.0.2"
Description = [ 'Fixed "set_env" import module references.',]
GitHubIssues = []

[0.0.2]
Title = "Version 0.0.2"
Description = [ 'Implement "set_env" & "adda"',]
GitHubIssues = []

[0.0.1]
Title = "Version 0.0.1"
Description = [ 'Implement "set_env" & "adda"',]
GitHubIssues = []

[0.0.0]
Title = "Version 0.0.0"
Description = [ "Creation of the project",]
GitHubIssues = [1]
