name: Pre-Commit and Document Check

on:
  workflow_call:

jobs:
  Pre-Commit:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        os: ['ubuntu-latest']
        python-version: ['3.12']

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Upgrade pip
        run: python -m pip install --upgrade pip

      - name: Install pre-requisits
        run: pip install pre-commit mdformat rstcheck

      - name: Run pre-commit checks
        uses: pre-commit/action@v3.0.1

  Document-Check:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        os: ['ubuntu-latest']
        python-version: ['3.12']

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Upgrade pip
        run: python -m pip install --upgrade pip

      - name: Install python requirements
        run: pip install pre-commit mdformat rstcheck

      - name: Run pre-commit checks
        uses: pre-commit/action@v3.0.1

#      - name: Check documents
#        run: rstcheck README.rst

      - name: Check documents
        run: mdformat .
