name: Build-and-Release-to-Pypi

on:
#  pull_request:
#  push:
  workflow_call:

jobs:
  Build-and-Release-to-Pypi:
    runs-on: ${{ matrix.os }}

    environment:
      name: pypi
      url: https://pypi.org/project/BEETools

    permissions:
      id-token: write
      contents: write
      issues: write
      pull-requests: write

    strategy:
      fail-fast: true
      matrix:
        os: ['ubuntu-latest']
        python-version: ['3.11']

    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Upgrade pip
        run: python -m pip install --upgrade pip

      - name: Install build dependencies
        run: python -m pip install build wheel

      - name: Build distributions
        shell: bash -l {0}
        run: python -m build

      - name: Set Git identity
        run: |
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"

      - name: Merge into master
        id: merge
        run: |
          git checkout master
          git merge --no-ff $GITHUB_REF
        continue-on-error: false

      - name: Push to master
        if: steps.merge.outcome == 'success'
        run: |
          git push origin master
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT_HDT }}

      - name: Publish package to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN_231021 }}
