name: CI

on:
  workflow_call:

jobs:
  CI:
    runs-on: ${{matrix.os}}
    strategy:
      fail-fast: true
      matrix:
#        python-version: ['3.8', '3.9', '3.10', '3.11']
        python-version: ['3.11']
#        os: ['ubuntu-latest', 'windows-latest', 'macos-latest']
        os: ['ubuntu-latest']

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64

      - name: Upgrade pip
        run: python -m pip install --upgrade pip

      - name: Install editable package
        run: pip install -e .[dev]

      - name: Run pytest
        run: pytest --cov=./

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
