name: Pre-Commit
on: [pull_request, push, workflow_dispatch]

env:
  GITIT_ISSUE_PREFIX: BEE

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - uses: pre-commit/action@v2.0.0
