name: Pre-Commit
on: [push, workflow_dispatch]

env:
  GITIT_ISSUE_PREFIX: BEE

jobs:
  lint:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        os: ["ubuntu-latest"]
        python-version: ["3.10.8"]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
      - uses: pre-commit/action@v2.0.0
